# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0002_auto_20180703_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
